# RSS Aggregator Feed Configuration
# Add one feed URL per line
https://dubroy.com/blog/rss.xml
https://lucumr.pocoo.org/feed.xml
https://healeycodes.com/feed.xml
https://benhoyt.com/writings/rss.xml
https://notes.eatonphil.com/rss.xml
https://mht.wtf/post/index.xml
https://jvns.ca/atom.xml
https://danluu.com/atom.xml
https://www.benkuhn.net/index.xml
http://www.aaronsw.com/2002/feeds/pgessays.rss
https://eli.thegreenplace.net/feeds/all.atom.xml
https://bcantrill.dtrace.org/index.xml
